version: "3.4"

services:
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionString=Server=localhost;Database=LoadTestDb;User=sa;Password=KtPm23GLP@ssW0rd!;Trust Server Certificate=true;Trusted_Connection=true;Persist Security Info=true;
      - MessageBroker__Host=amqp://localhost:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    depends_on:
      - catalog-mssql-db
  
  catalog-mssql-db:
    container_name: catalog-mssql-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD="KtPm23GLP@ssW0rd!"
    volumes:
      - mssql-data:/var/opt/mssql
  
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.11.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  mssql-data:
    driver: local