version: "3.4"

services:
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionString=${CONNECTION_STRING}
      - MessageBroker__Host=${MESSAGE_BROKER_HOST}
      - MessageBroker__Username=${MESSAGE_BROKER_USERNAME}
      - MessageBroker__Password=${MESSAGE_BROKER_PASSWORD}
    depends_on:
      - catalog-mssql-db
      - rabbitmq
  
  catalog-mssql-db:
    container_name: catalog-mssql-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
  
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.11.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  mssql-data:
    driver: local