version: "3.4"

services:
  catalog-api:   
    build:
      context: .
      dockerfile: Dockerfile        
    ports:                      
      - "8080:80"                   
    depends_on:
      - catalog-db
    
  catalog-db:    
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD="KtPm23GLP@ssW0rd!"
      
