name: Build solution

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-dotnet-project:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/Catalog.sln

      - name: Build .NET Project
        run: dotnet build ./src/Catalog.sln --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test ./src/Catalog.Tests/Catalog.Tests.csproj --configuration Release --no-build
        env:
          CollectCoverage: true
          CoverletOutputFormat: lcov
          ThresholdStat: total
          ThresholdType: Line
          CoverletOutput: TestResults/
          ConnectionString: 'Server=localhost,1433;Database=CatalogDb;User=sa;Password=gk+&42JV*Kvd4S6n-Px9;Trust Server Certificate=true;Persist Security Info=true;'
          MessageBroker__Host: rabbitmq
          MessageBroker__Username: guest
          MessageBroker__Password: guest